on:
  push:
    branches:
      - main

name: Build To-Do App

jobs:
  build:
    name: Build and release new APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get
        working-directory: frontend
      
      - name: Build Flutter APK
        run: flutter build apk --release --split-per-abi
        working-directory: frontend
      
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "frontend/build/app/outputs/apk/release/*"
          tag: v1.0.0
          token: ${{ secrets.TO_DO_APP_TOKEN }}